version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ".:/code"
    ports:
      - "8000:8000"
    depends_on:
      - db
  front:
    build: ./front
    ports:
      - "4200:4200"
    command: ["ng", "serve", "--host", "0.0.0.0"]
    volumes:
      - "./front:/usr/src/app"
      - "/usr/src/app/node_modules"
