# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='category',
            field=models.ManyToManyField(related_name='references', to='catalogue.Category'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='url',
            field=models.CharField(max_length=250),
        ),
    ]
